### ISSUE TITLE
Create a css file

### ISSUE THREAD

**Issue by romanx2012** [romanx2012/personal_website#5]
TERMINAL!!!!

**Comment by whovibhor** [comment]
**Creating CSS Files: The Basics**

The core idea is simple: CSS files are just text files with a `.css` extension. Inside, you write rules that tell your website how to look.

**Method 1: Notepad (For Windows Users)**

Notepad is the trusty, no-frills text editor built into Windows. Here's how to use it for CSS:

1.  **Open Notepad:** Find it in your Start Menu (usually under "Windows Accessories").
2.  **Write Your CSS:** Type in your CSS rules.  Here's a simple example:

    ```css
    body {
      font-family: sans-serif;
      background-color: #ffffff;
    }

    h1 {
      color: #000080;
      text-align: center;
    }
    ```

3.  **Save the File:**
    *   Go to `File > Save As...`
    *   **Crucial Part:** In the "Save as type" dropdown, choose "All Files". This stops Notepad from adding a `.txt` extension.
    *   **Name Your File:** Give it a name ending in `.css` (like `styles.css` or `main.css`). The name itself is up to you.
    *   **Encoding:** Ensure the encoding is set to `UTF-8`.
    *   **Save Location:** Pick a folder where you'll keep your website files (or a subfolder called "css").

**Method 2: Visual Studio Code (VS Code) (Any OS)**

VS Code is a more powerful, free code editor that makes CSS creation much smoother.

1.  **Open VS Code:** Launch the program.
2.  **Create a New File:** Go to `File > New File` (or press Ctrl+N / Cmd+N).
3.  **Immediately Save:** Go to `File > Save As...` (or Ctrl+Shift+S / Cmd+Shift+S). This is important!
4.  **Name and Save:**
    *   Name the file with a `.css` extension (e.g., `site.css`).
    *   VS Code *usually* recognizes it as a CSS file at this point, but if not, look for a "Save as type" option and select "CSS" or "All Files".
    *   Save it to your project's folder (or a "css" subfolder).

**Basic CSS Syntax: Key Concepts**

CSS rules have this basic structure:

```css
selector {
  property: value;
}
```

*   **Selector:** This is what you're styling. It could be an HTML element (`body`, `h1`, `p`), a class (`.my-class`), or an ID (`#my-id`).
*   **Property:** This is the aspect you want to change (e.g., `color`, `font-size`, `background-color`).
*   **Value:** This is what you want to set the property to (e.g., `blue`, `16px`, `#f0f0f0`).

**Example Breakdown:**

```css
h1 {
  color: blue; /* Sets the text color of all h1 headings to blue */
  text-align: center; /* Centers the text horizontally within the h1 */
}

p {
  font-size: 14px; /* Sets the font size of all paragraphs to 14 pixels */
  line-height: 1.5; /* Sets the line spacing to 1.5 times the font size */
}

.highlight { /* This is a class selector */
  background-color: yellow; /* Sets the background color of any element with the class "highlight" to yellow */
}

#main-title { /* This is an ID selector */
  font-weight: bold; /* Makes the text bold for the element with the ID "main-title" */
}
```

*   `/* This is a comment */`:  Use comments to explain your code.
*   **Colors:**  Colors can be specified by name (`blue`, `red`), hex code (`#0000FF`, `#FF0000`), or `rgb()` values.

**Linking Your CSS to Your HTML**

To make your CSS work, you need to link it to your HTML file. Put this inside the `<head>` section of your HTML:

```html
<!DOCTYPE html>
<html>
<head>
  <title>My Page</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <h1>Hello, world!</h1>
  <p>This is some text.</p>
</body>
</html>
```

*   `href="styles.css"`:  Make sure the path to your CSS file is correct. If your CSS file is in a folder called "css", the `href` would be `href="css/styles.css"`.

That's the foundation. Start experimenting with different properties and values to see how they change your website's appearance.
